modLoader="javafml"
loaderVersion="[47,)"

license="LGPL-2.1-or-later"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
modId="fallen_traits"
version="1.20.1-1.0.0"
displayName="Fallen Traits"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
credits="me"
authors="Kayn"
description='''
  An L2 Hostility addon which intergrates a bunch of other mods with it
  '''
displayTest="MATCH_VERSION"

[[dependencies.fallen_traits]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.fallen_traits]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.fallen_traits]]
modId="l2library"
mandatory=true
versionRange="[2.4.23,)"
ordering="AFTER"
side="BOTH"
[[dependencies.fallen_traits]]
modId="l2complements"
mandatory=true
versionRange="[2.4.29,)"
ordering="AFTER"
side="BOTH"
[[dependencies.fallen_traits]]
modId="l2hostility"
mandatory=false
versionRange="[2.5.6,)"
ordering="AFTER"
side="BOTH"
[[dependencies.fallen_traits]]
modId="l2tabs"
mandatory=true
versionRange="[0.2.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.fallen_traits]]
modId="curios"
mandatory=true
versionRange="[5.4.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_traits]]
modId="irons_spellbooks"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_traits]]
modId="cataclysm"
mandatory=true
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"
