modLoader="javafml"
loaderVersion="[47,)"

license="LGPL-2.1-or-later"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
modId="apotheotic_hostility"
version="1.20.1-1.0.0"
displayName="Apotheotic Hostility"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
credits="me"
authors="Kayn"
description='''
  A mod that integrates L2Hostility and Apotheosis together
  '''
displayTest="MATCH_VERSION"

[[dependencies.apotheotic_hostility]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="l2library"
mandatory=true
versionRange="[2.4.23,)"
ordering="AFTER"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="l2complements"
mandatory=true
versionRange="[2.4.29,)"
ordering="AFTER"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="l2hostility"
mandatory=false
versionRange="[2.5.6,)"
ordering="AFTER"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="l2tabs"
mandatory=true
versionRange="[0.2.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.apotheotic_hostility]]
modId="curios"
mandatory=true
versionRange="[5.4.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.apotheotic_hostility]]
modId="apotheosis"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
